fix(build): correctly handle lto settings
when bumping your rust version, enabling LTO can cause confusing ldd
errors, e.g.

error: Invalid summary version 12. Version should be in the range [1-10]

the check for enabling LTO also wasn't correct meaning it would always
be enabled, now it is disabled by default and only enabled when
GLIDE_LTO is set