fix(devtools): avoid random autocomplete failures
seemingly randomly, in my release build the dev tools *web* console
would not autocomplete anything. checking the browser toolbox yielded
this error

Error: Encountered error while waiting for Helper Result: [Exception...
"Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE)
[nsIPrefBranch.setBoolPref]"  nsresult: "0x80040111
(NS_ERROR_NOT_AVAILABLE)"  location: "JS frame ::
resource://devtools/server/actors/webconsole.js :: get evalGlobal ::
line 281"  data: no]

which pointed to our code that checks a pref in the devtools actor,
which is pointless in the web devtools... now we just ignore any errors
that happen while checking it.